export const images = {
  adaptiveIcon: require("./adaptive-icon.png"),
  androidIconBackground: require("./android-icon-background.png"),
  androidIconForeground: require("./android-icon-foreground.png"),
  androidIconMonochrome: require("./android-icon-monochrome.png"),
  avatar: require("./avatar.png"),
  avocado: require("./avocado.png"),
  bacon: require("./bacon.png"),
  burgerOne: require("./burger-one.png"),
  burgerTwo: require("./burger-two.png"),
  buritto: require("./buritto.png"),
  cheese: require("./cheese.png"),
  coleslaw: require("./coleslaw.png"),
  cucumber: require("./cucumber.png"),
  emptyState: require("./empty-state.png"),
  favicon: require("./favicon.png"),
  fries: require("./fries.png"),
  icon: require("./icon.png"),
  loginGraphic: require("./login-graphic.png"),
  logo: require("./logo.png"),
  mozarellaSticks: require("./mozarella-sticks.png"),
  mushrooms: require("./mushrooms.png"),
  onionRings: require("./onion-rings.png"),
  onions: require("./onions.png"),
  partialReactLogo: require("./partial-react-logo.png"),
  pizzaOne: require("./pizza-one.png"),
  reactLogo: require("./react-logo.png"),
  reactLogoX2: require("./react-logo@2x.png"),
  reactLogoX3: require("./react-logo@3x.png"),
  salad: require("./salad.png"),
  splashIcon: require("./splash-icon.png"),
  success: require("./success.png"),
  tomatoes: require("./tomatoes.png"),
};

export default images;
